### ISSUE TITLE
GzipFile not allowed for tarfile.open(fileobj=...)

### ISSUE THREAD

**Issue by asottile** [python/typeshed#5491]
minimal reproduction:

```python
import gzip
import tarfile


open('t', 'w').close()
with gzip.GzipFile('out.tar.gz', 'wb') as gzipf:
    with tarfile.open(fileobj=gzipf, mode='w') as tf:
        tf.add('t')
```

```console
$ python3 t.py 
$ mypy t.py
t.py:7: error: Argument "fileobj" to "open" has incompatible type "GzipFile"; expected "Optional[IO[bytes]]"
Found 1 error in 1 file (checked 1 source file)
$ mypy --version
mypy 0.812
```

presumably `fileobj` should use a `Protocol` of some shape ?

**Comment by hauntsaninja** [comment]
I think this just got fixed in https://github.com/python/typeshed/issues/5099

**Comment by asottile** [comment]
appears not fixed:

```console
$ mypy --custom-typeshed-dir /tmp/typeshed/ t.py 
t.py:7: error: Argument "fileobj" to "open" has incompatible type "GzipFile"; expected "Optional[IO[bytes]]"
Found 1 error in 1 file (checked 1 source file)
$ mypy --version
mypy 0.820+dev.675ae1afc8a5b0a9a515292c7e9d6bc2a38887be
$ git -C ../typeshed/ rev-parse HEAD
7d4ecf7f0a64cbfab59e54c8df1d5c53bcd9b9a1
```

**Comment by ethanhs** [comment]
It looks like https://github.com/python/typeshed/pull/5170 fixed `GzipFile`, but not `tarfile`.

**Comment by JelleZijlstra** [comment]
As discussed the PR doesn't fix this issue, which is about `tarfile.open`. We still need to convert `tarfile.open` to overloads + IO protocols.

**Comment by max-muoto** [comment]
We should be able to close this out now @JelleZijlstra.
